set -s default-terminal 'tmux-direct'
set -sa terminal-features 'xterm-256color:RGB:extkeys'
set -gF default-shell '#{APPDIR}/usr/bin/zsh'

set -g prefix C-a
bind C-a send-prefix
unbind C-b

source-file -q /etc/tmux.conf
